name: Build

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Maven, p2 and Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.gradle
            !~/.m2/**/*mavenized*
            !~/.m2/**/*example*
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Build
        run: |
          mvn clean install -U
          cd example-project
          mvn clean verify -U
          cd ../example-project-gradle
          ./gradlew clean build
